<?php
/**
 * Test class for Basket.
 * Generated by PHPUnit on 2011-02-04 at 17:50:55.
 */
class BasketTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Basket
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $app    = App::getInstance();
        $this->object = $app->getBasket();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     */
    public function testAdd()
    {
        $this->object->add( null, 'product', 7, 5.55, 'some info' );

        $products   = $this->object->getAll();

        $found  = false;
        foreach ( $products as $product ) {
            if ( $product['name'] == 'product' ) {
                $found  = true;
                $this->assertEquals( $product['count'], 7, 'Count not equal' );
                $this->assertEquals( $product['price'], 5.55, 'Price not equal' );
                $this->assertEquals( $product['details'], 'some info', 'Details not equal' );
            }
        }

        $this->assertTrue( $found, 'Product not found' );
        $this->assertEquals( count( $this->object->getAll() ), 1, 'Product not added' );
    }

    /**
     */
    public function testSetCount()
    {
        $this->assertTrue( $this->object->setCount('product', 10) );
        $products   = $this->object->getAll();

        foreach ( $products as $product ) {
            if ( $product['name'] == 'product' ) {
                $this->assertEquals( $product['count'], 10 );
                break;
            }
        }
    }

    /**
     */
    public function testGetCount()
    {
        $this->assertEquals( $this->object->getCount('product'), 10, 'Count not correspond test value' );
        $this->object->add( 0, 'prod2', 5, 7.66, 'test prod');
        $this->assertEquals( $this->object->getCount(), 15, 'Count not correspond test value' );
        $this->object->add( 0, 'product', 5, 5.65, 'prod for test');
        $this->assertEquals( $this->object->getCount(), 20, 'Count not correspond test value' );
    }

    /**
     */
    public function testGetPrice()
    {
        $this->assertEquals( $this->object->getPrice('product'), 5.55 );
        $this->assertEquals( $this->object->getPrice('prod2'), 7.66 );
    }

    /**
     */
    public function testCount()
    {
        $this->assertEquals( $this->object->count(), 3 );
    }

    /**
     */
    public function testGetSum()
    {
        $this->assertEquals( 83.75, $this->object->getSum('product') );
        $this->assertEquals( 38.3, $this->object->getSum('prod2') );
        $this->assertEquals( 122.05, $this->object->getSum() );
    }

    /**
     */
    public function testGetAll()
    {
        $this->assertEquals( count( $this->object->getAll() ), 3 );
    }

    /**
     */
    public function testDel()
    {
        // @TODO тут надо уточнять параметры, по которым удаляется продукт
        $this->object->del(0, 7);
        $this->assertEquals( 8, $this->object->getCount('product') );
        $this->object->del(0);
        $this->assertEquals( 5, $this->object->getCount('product') );
    }

    /**
     */
    public function testClear()
    {
        $this->object->clear();
        $this->assertEquals( count( $this->object->getAll() ), 0 );
    }
}
