<?php
/**
 * Test class for Request.
 * Generated by PHPUnit on 2011-02-04 at 16:39:55.
 */
use Sfcms\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\Storage\MockArraySessionStorage;

class RequestTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Request
     */
    protected $request;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $_GET['_format'] = 'html';
        $this->request = Request::create('/', 'GET', array(
                'test1' => 'test1',
                'test2' => 'test2',
                'email' => 'foo@example.com',
                'test' => array('foo' => 'foo'),
                'digit' => 5,
            ));
        $this->request->setSession(new Session(new MockArraySessionStorage()));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     */
    public function testGetAjax()
    {
        $this->assertFalse( $this->request->getAjax() );
    }

    /**
     */
    public function testIsAjax()
    {
        $this->assertFalse( $this->request->isAjax() );
    }

    /**
     * @covers Sfcms\Request::getAjaxType
     */
    public function testGetAjaxType()
    {
        $this->assertEquals('html', $this->request->getRequestFormat());
        $this->assertEquals('html', $this->request->getAjaxType());
    }

    /**
     */
    public function testGetError()
    {
        $this->assertEquals($this->request->getError(), 0, 'Error found');
    }

    /**
     */
    public function testSetError()
    {
        $this->request->setError(7);
        $this->assertEquals( $this->request->getError(), 7, 'Digit error test fail' );

        $this->request->setError('Text');
        $this->assertEquals( $this->request->getError(), 'Text', 'Text error test fail' );
    }

//    public function testGetStyle()
//    {
//        $this->markTestSkipped();
//        $styles = $this->request->getStyle();
//
//        $this->assertTrue(is_array( $styles ), 'Styles list not Array');
//        $this->assertEquals( count( $styles ), 3, 'Count default styles not equal 3' );
//    }

//    public function testAddStyle()
//    {
//        $this->markTestSkipped();
//        $this->request->addStyle('/css/style.css');
//
//        $styles = $this->request->getStyle();
//
//        $this->assertEquals( count( $styles ), 4, 'Count styles not equal 4' );
//
//        $found = false;
//        foreach ( $styles as $style ) {
//            if ( $style == '/css/style.css' ) {
//                $found = true;
//            }
//        }
//        $this->assertTrue( $found, 'Added style not found' );
//    }

//    public function testCleanStyle()
//    {
//        $this->markTestSkipped();
//        $this->request->cleanStyle();
//        $this->assertEquals( count( $this->request->getStyle() ), 0, 'Styles list not cleared' );
//    }

//    public function testGetScript()
//    {
//        $this->markTestSkipped();
//        $scripts    = $this->request->getScript();
//        $this->assertTrue( is_array( $scripts ), 'Scripts list fail format' );
//        $this->assertEquals( count( $scripts ), 3, 'Default scripts list count not equal 2' );
//    }

//    public function testAddScript()
//    {
//        $this->markTestSkipped();
//        $this->request->addScript('/js/script.js');
//
//        $scripts = $this->request->getScript();
//
//        $this->assertEquals( count( $scripts ), 4, 'Count scripts not equal 3' );
//
//        $found = false;
//        foreach ( $scripts as $script ) {
//            if ( $script == '/js/script.js' ) {
//                $found = true;
//            }
//        }
//        $this->assertTrue( $found, 'Added script not found' );
//    }

//    public function testCleanScript()
//    {
//        $this->markTestSkipped();
//        $this->request->cleanScript();
//        $this->assertEquals( count( $this->request->getScript() ), 0, 'Scripts list not cleared' );
//    }

    public function testSet()
    {
        $this->request->query->set('test', 'test_value');
        $this->assertEquals('test_value', $this->request->get('test'));
    }

    public function testGet()
    {
        $this->assertEquals(5, $this->request->get('digit'), 'Int value fail');
        $this->assertEquals('test1', $this->request->get('test1'), 'String value fail');
        $this->assertEquals('test2', $this->request->get('test2'), 'String value fail');
        $this->assertEquals('foo@example.com', $this->request->get('email'), 'Email value fail');
        $this->assertTrue(is_array( $this->request->get('test') ), 'Array value getted not as array');
        $test = $this->request->get('test');
        $this->assertEquals($test['foo'], 'foo', 'Chain do not work');
    }

    public function testGetNol()
    {
        $this->request->set('nol', 0);
        $this->assertEquals(0, $this->request->get('nol'));
    }

    /**
     */
//    public function testSetContent()
//    {
//        $this->request->setContent('My content');
//        $this->assertEquals($this->request->getContent(), 'My content', 'Broken content information');
//    }

    /**
     */
//    public function testGetContent()
//    {
//        $this->request->setContent('My content');
//        $this->assertEquals($this->request->getContent(), 'My content', 'Broken content information');
//    }

    /**
     */
    public function testSetTitle()
    {
        $this->request->setTitle('My content');
        $this->assertEquals($this->request->getTitle(), 'My content', 'Broken title information');
    }

    /**
     */
    public function testGetTitle()
    {
        $this->request->setTitle('My content');
        $this->assertEquals($this->request->getTitle(), 'My content', 'Broken title information');
    }

/*    public function testGetResponseAsXML()
    {
        $this->request->setResponseError(10,'test error');
        $this->assertEquals("<?xml version=\"1.0\"?>\n<response><error>10</error><msg>test error</msg></response>\n",
            $this->request->getResponseAsXML());
    }*/
}
