<?php
use Module\User\Controller\UserController;

/**
 * Test class for Controller_Users.
 * Generated by PHPUnit on 2012-04-20 at 20:50:17.
 */
class Controller_UsersTest extends \Sfcms\Test\TestCase
{
    /**
     * @var UserController
     */
    protected $controller;

    /**
     * @var \Sfcms\Request
     */
    protected $request;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->controller = new UserController($this->request);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Инициализвция
     */
    public function testInit()
    {
        $this->assertEquals('inner', $this->request->get('template') );
    }

    /**
     * Права доступа
     */
    public function testAccess()
    {
        $access = $this->controller->access();
        $this->assertArrayHasKey(USER_ADMIN, $access);
        $this->assertContains('admin', $access[USER_ADMIN]);
        $this->assertContains('adminEdit', $access[USER_ADMIN]);
        $this->assertContains('save', $access[USER_ADMIN]);
    }

    /**
     * Действие по умолчанию
     */
    public function testIndexAction()
    {
        $return = $this->controller->indexAction( null, null );
        $result = $this->request->getContent();

        $this->assertStringStartsWith('<form action="/user/login" class="form-horizontal"', trim( $return ) );
        $this->assertEmpty( $result );
    }

    /**
     * Действие админа
     */
    public function testAdminAction()
    {
        $return = $this->controller->adminAction();
        $result = $this->request->getContent();
        $this->assertEmpty( $result );
        $this->assertStringStartsWith('<form action', $return);
    }

    /**
     * Редактирование пользователя в админке
     */
    public function testAdminEditAction()
    {
        $return = $this->controller->adminEditAction( null );
        $result = $this->request->getContent();
        $this->assertArrayHasKey('form', $return );
        $this->assertEmpty( $result );
    }

    /**
     * Сохранение
     */
    public function testSaveAction()
    {
        $return = $this->controller->saveAction();
        $result = $this->request->getContent();

        $this->assertEmpty($result);
        $this->assertEquals('Data not sent', $return);
    }

    /**
     * Вход
     */
    public function testLoginAction()
    {
        $return = $this->controller->indexAction( null, null );
        $result = $this->request->getContent();
        $this->assertStringStartsWith('<form action="/user/login" class="form-horizontal"', trim( $return ) );
        $this->assertEmpty( $result );
    }

    /**
     * Кабинет
     */
    public function testCabinetAction()
    {
//        $return = $this->controller->cabinetAction();
    }

    /**
     * Правка профиля
     */
    public function testEditAction()
    {
        $return = $this->controller->editAction( null );
        $result = $this->request->getContent();
        $this->assertEmpty($result);
        $this->assertInternalType('array', $return);
        $this->arrayHasKey('form', $return);
        $this->assertInstanceOf( '\Forms\User\Profile', $return['form']);
    }

    /**
     * Регистрация
     */
    public function testRegisterAction()
    {
        $return = trim( $this->controller->registerAction() );
        $result = $this->request->getContent();
        $this->assertEmpty($result);
        $this->assertStringStartsWith('<form action="" class="standart" enctype="multipart/form-data" id="form_register"', $return);
    }

    /**
     * Восстановление
     */
    public function testRestoreAction()
    {
        $return = $this->controller->restoreAction();
        $result = $this->request->getContent();

        $this->assertEmpty($result);

        $this->assertInternalType('array', $return);
        $this->arrayHasKey('form', $return);
        $this->assertInternalType('string', $return['form']->html());
        $this->assertStringStartsWith(
            '<form action="/user/restore" class="form-horizontal" '
                . 'enctype="multipart/form-data" id="form_restore" method="post" name="form_restore"',
            $return['form']->html()
        );
    }

    public function testRecoveryAction()
    {
        $return = $this->controller->recoveryAction(null,null);
        $result = $this->request->getContent();

        $this->assertEmpty( $result );

        $this->assertInternalType('array',$return);
        $this->assertArrayHasKey('error', $return);
        $this->assertEquals(1, $return['error']);
        $this->assertArrayHasKey('msg', $return);
        $this->assertEquals("Не указаны параметры восстановления",$return['msg']);

        $return = $this->controller->recoveryAction('sdsadsd@ermin.ru','123232afsdfsdfs');
        $this->assertInternalType('array',$return);
        $this->assertArrayHasKey('error', $return);
        $this->assertEquals(1, $return['error']);
        $this->assertArrayHasKey('msg', $return);
        $this->assertEquals("Ваш email не найден",$return['msg']);

        $return = $this->controller->recoveryAction('admin@ermin.ru','123232afsdfsdfs');
        $this->assertInternalType('array',$return);
        $this->assertArrayHasKey('error', $return);
        $this->assertEquals(1, $return['error']);
        $this->assertArrayHasKey('msg', $return);
        $this->assertEquals("Неверный код восстановления",$return['msg']);
    }

    /**
     * Пароль
     */
    public function testPasswordAction()
    {
        $return = $this->controller->passwordAction();
        $result = $this->request->getContent();

        $this->assertEmpty($result);
        $this->assertStringStartsWith(
            '<form action="" class="form-horizontal" enctype="multipart/form-data" id="form_password"',
            $return
        );
    }
}
