#!/usr/bin/env php
<?php
set_time_limit(0);

//корень сайта
define('ROOT', realpath(__DIR__.'/..'));

require_once ROOT . '/vendor/autoload.php';

use Module\Doctrine\Manager\DoctrineManager;
use Sfcms\ConsoleApplication;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Symfony\Component\Console\Helper\DialogHelper;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$kernel = new \App($env, $debug);
$kernel->isConsole(true);

$app = new ConsoleApplication($kernel);

/** @var DoctrineManager $doctrineManager */
$doctrineManager = $kernel->getContainer()->get('doctrine.manager');
$app->setHelperSet(ConsoleRunner::createHelperSet($doctrineManager->getEntityManager()));
$app->getHelperSet()->set(new DialogHelper(), 'dialog');

$app->run($input);
