#!/usr/bin/env php
<?php
set_time_limit(0);

//корень сайта
define('ROOT', realpath(__DIR__.'/..'));

require_once ROOT . '/vendor/autoload.php';

use Sfcms\Console;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$kernel = new \App($env, $debug);
$kernel->isConsole(true);

$console = new Console($kernel);
$console->run($input);
