<?php
/**
 * This file was generated by SiteForeverGen
 */
return array(
    Module\System\Module::class,
    Module\Database\Module::class,
    Module\Dashboard\Module::class,
    Module\Page\Module::class,
    Module\Translator\Module::class,
    Module\Smarty\Module::class,
    Module\Robokassa\Module::class,
    Module\User\Module::class,
    Module\News\Module::class,
    Module\Banner\Module::class,
    Module\Gallery\Module::class,
    Module\Guestbook\Module::class,
    Module\Catalog\Module::class,
    Module\Feedback\Module::class,
    Module\Market\Module::class,
    Module\Elfinder\Module::class,
    Module\Test\Module::class,
);
