<?php
/**
 * This file was generated by SiteForeverGen
 */
return array(
    array('name' => 'System', 'path' => 'Module\System'),
    array('name' => 'Database', 'path' => 'Module\Database'),
    //array('name' => 'Doctrine', 'path' => 'Module\Doctrine'),
    array('name' => 'Dashboard', 'path' => 'Module\Dashboard'),
    array('name' => 'Page', 'path' => 'Module\Page'),
    array('name' => 'Translator', 'path' => 'Module\Translator'),
    array('name' => 'Smarty', 'path' => 'Module\Smarty'),
    array('name' => 'Robokassa', 'path' => 'Module\Robokassa'),
    array('name' => 'User', 'path' => 'Module\User'),
    array('name' => 'News', 'path' => 'Module\News'),
    array('name' => 'Banner', 'path' => 'Module\Banner'),
    array('name' => 'Gallery', 'path' => 'Module\Gallery'),
    array('name' => 'Guestbook', 'path' => 'Module\Guestbook'),
    array('name' => 'Catalog', 'path' => 'Module\Catalog'),
    array('name' => 'Feedback', 'path' => 'Module\Feedback'),
    array('name' => 'Market', 'path' => 'Module\Market'),
    array('name' => 'Search', 'path' => 'Module\Search'),
    array('name' => 'Elfinder', 'path' => 'Module\Elfinder'),
    //array('name' => 'Generator', 'path' => 'Module\Generator'),
    //array('name' => 'Monolog', 'path' => 'Module\Monolog'),
    array('name' => 'Test', 'path' => 'Module\Test'),
);
